---
enable_subscription: true
is_vagrant: false
rhsm_org: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66346638313865643131323535643439393464386536636432616366306564333934633464656137
          3138316536336637663861366562633430623531663864650a326438613536353735333763636335
          66383934396235386236636365326335613538646232643666313761653763643766633965336635
          3066393335646463650a333634316535616333353464633362653530633332306562333536626365
          6533
rhsm_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36626563633963333638363166336535313664636531353230636266656261613234366133346261
          3437656530653834623964633264393961636331613934640a353839656231663535393239396334
          30356164336138613266616264373663303631336661643666323132373132336161663139643333
          3336376230623063360a333862616461366164346264613466393866613432313532336163353963
          61373532343063383062613235613030623037636463613531393236363735316632
nvidia_driver_url: "https://us.download.nvidia.com/XFree86/Linux-x86_64/550.78/NVIDIA-Linux-x86_64-550.78.run"
nvidia_driver_file: "{{ nvidia_driver_url | basename }}"


users:
  - name: justin
    password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              38303632356431366366346464646164373936356238333863356635306564303534336666383432
              3531356366333964636430373361616661633364323730350a626330666533633335643063303930
              35303535386639366536383935613438353433373235363037323566633162653137313931643835
              6662646233323562630a383061393939343237306130643763656631363463653164393463356434
              38306461656364633763353566353061303933376463663763363231333937333532386339396265
              64646535393031383132386336653937323833663237386139646133313764623161396464616166
              65336531653737313439663966316636646239353837353237303337616565313561333433373835
              61646433373263613730303530363861653965653937303030336338643031386239313232633739
              32373037376536616665303264653261353437373935336461353833643631663036
    shell: /bin/zsh
    groups: [wheel]
    system: false
    enable_podman: true
    directories: []

  - name: sd-data
    shell: /sbin/nologin
    system: true
    enable_podman: true
    directories:
      - /home/sd-data
      - /home/sd-data/data
