---
rhsm_org: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66346638313865643131323535643439393464386536636432616366306564333934633464656137
          3138316536336637663861366562633430623531663864650a326438613536353735333763636335
          66383934396235386236636365326335613538646232643666313761653763643766633965336635
          3066393335646463650a333634316535616333353464633362653530633332306562333536626365
          6533
rhsm_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36626563633963333638363166336535313664636531353230636266656261613234366133346261
          3437656530653834623964633264393961636331613934640a353839656231663535393239396334
          30356164336138613266616264373663303631336661643666323132373132336161663139643333
          3336376230623063360a333862616461366164346264613466393866613432313532336163353963
          61373532343063383062613235613030623037636463613531393236363735316632
